name: example
description: Assimp for Dart example app
publish_to: 'none'

environment:
  sdk: '>=2.7.0 <3.0.0'

dependencies:
  assimp:
    path: ../
  flutter:
    sdk: flutter
  path:
  vector_math:

flutter:
  assets:
    - models/box.obj
    - models/box.3mf
    - models/mug.obj
    - models/spider.3mf
  uses-material-design: true
