name: assimp
version: 0.0.6
description: >-
  Open Asset Import Library aka Assimp for Dart. Assimp can import
  various well-known 3D model formats in a uniform manner.
homepage: https://github.com/jpnurmi/dart_assimp
repository: https://github.com/jpnurmi/dart_assimp
issue_tracker: https://github.com/jpnurmi/dart_assimp/issues

environment:
  sdk: '>=2.7.0 <3.0.0'
dependencies:
  ffi: ^0.1.3
  meta: ^1.1.8
  quiver: ^2.1.3
  vector_math: ^2.0.8
dev_dependencies:
  path: ^1.7.0
  test: ^1.14.7
  test_coverage: ^0.4.1
