name: assimp
version: 0.1.0-dev.0

environment:
  sdk: ">=2.17.0 <4.0.0"

dependencies:
  dylib: ^0.3.2+1
  equatable: ^2.0.0
  ffi: ^2.1.4
  meta: ^1.3.0
  quiver: ^3.0.0
  vector_math: ^2.1.0

dev_dependencies:
  ffigen: ^19.0.0
  path: ^1.8.0
  test: ^1.17.3
  test_cov: ^1.0.1